### ISSUE TITLE
Unable to recognize an issue. 

### ISSUE THREAD

**Issue by ghost** [r24y/quick-issues#1]
Hello, first off I like the app! I just downloaded it and it seems to be recognizing most of my issues without a problem, however, it fails to recognize an older issue of mine. 

My intuition tells me that it has something to do with being an older issue. For instance, maybe, there is a range of issues that get displayed, but older ones get left out as to not clutter the issue log? Regardless, I thought I would let you know about it incase it is a bug! :smile: 

[Here](https://github.com/JordanDworaczyk/Pricebots/issues/17) is the issue of mine that is not being displayed. I will provide a screen shot of my atom.io editor below: 

![capture](https://user-images.githubusercontent.com/19294959/27774257-35c1e43e-5f43-11e7-9cf9-4ef269f2488e.PNG)

I am not sure, what the problem could be. But, I hope you could address it quickly. Keep up the good work! 😎

**Comment by ryaninvents** [comment]
Hi! Glad you like the package!

In the dropdown menu at the top-right, have you tried changing "Open" to either "Closed" or "All"? The issue you linked to is closed, so it would not show up in the default view (which is only "Open" issues).

I'll leave this issue open since there's some non-intuitive UI behavior here that can be improved upon.

**Comment by ryaninvents** [comment]
Version 0.9.3 now displays a small message when a filter is applied. The previous behavior was too confusing since issues were simply missing with no explanation.

![screen shot 2017-07-05 at 12 23 32 pm](https://user-images.githubusercontent.com/8356669/27874224-ce4aa368-617c-11e7-9fcd-9715ddeffefb.png)

**Comment by ghost** [comment]
Ah, let me do better to document the failure mode. I had closed that linked issue since I was working on it at the time and had finished it. It did not occur to me that closing the issue would interfer with this trouble shooting process because I had forgot that I linked it to you. 😆 

The root cause could have been, as you mentioned, that I had the issue closed all along. It is a too tricky to say since we don't know exactly when I had closed the issue. But, this may very well have been the case. ( I would not have been the first to commit user error in my lifetime. 😉 )

Howeveer, here is another failure to recognize an issue. In this case my issue can be seen [here](https://github.com/JordanDworaczyk/Pricebots/issues/6). 

Issues | Atom.io
-------|---------------
![capture](https://user-images.githubusercontent.com/19294959/27890954-3504f5bc-61ab-11e7-8d0c-5927fb2223f6.PNG) | ![capture2](https://user-images.githubusercontent.com/19294959/27890970-4af85850-61ab-11e7-9e68-c0b00cdb685d.PNG)

As you can see in the Atom.io Issue [#6](https://github.com/JordanDworaczyk/Pricebots/issues/6) is now showing up. I can change the filters between _Open, Closed, and All_, but that issue still doesn't show up. 

I do realize that I have the older version. I will update the version in a moment, but I wanted to show you this first. I think that that the change that you made in v0.9.3 is a good touch though. Please, if you have any questions let me know! 😄

**Comment by ryaninvents** [comment]
I think I see the problem! Looks like there are more issues than can fit on one page of API results. Currently `quick-issues` only fetches a single page. I'll have to think about how best to handle this but at least it's clear now what the problem is.
