### ISSUE TITLE
Uncaught (in promise) Repo not found for: E:\projects\my-project

### ISSUE THREAD

**Issue by AionDev** [r24y/quick-issues#4]
When selecting `my-project -> right click -> Github Issues`  nothing happens.
I opened up the console and i see error:
```
Uncaught (in promise) Repo not found for: E:\projects\my-project
```
In my package.json i set up the repository field.
```
"repository" :
  { "type" : "git"
  , "url" : "https://github.com/.. my-project"
  },
```
I restarted atom. Still doesn't work.
Is there something more i should be doing ? Some other configuration? Thanks 😄

**Comment by ryaninvents** [comment]
If you run `git remote show origin` inside the repo, what is the output?

**Comment by AionDev** [comment]
@r24y i think is a good idea if you close this issue. 
I reinstalled atom a bunch of times since i had this bug. 
I don't have it anymore - and i don't know how to replicate it either. Thanks :)
