### ISSUE TITLE
Not working..

### ISSUE THREAD

**Issue by Anonymous142** [r24y/quick-issues#6]
not working on 1.24.0-beta3 x64, windows 10 rs1 64bit
'Open On GitHub' package' is working.

**Comment by ryaninvents** [comment]
Would you mind adding a bit more detail to this, so I can better figure out the problem you're having? For instance, any of these would be good:

- Screenshots
- Description of workspace (for instance, "workspace contains two projects, one of which is a GitHub repo")
- Remote URL used for GitHub repo (if private, just say it's a private repo)

**Comment by Anonymous142** [comment]
oh sorry, It's working now.
I think there are some sync delay..
I have some wishes.

1. Issues writing
If I can write issues with this package, it would be great.

2. Auto start
Atom's Git tab and GitHub tab, both are auto start.. i think if also issues tab start together, it would be good.

3. UI customizing
In small sized tab(under 300px), "Fetching Issues" animations are cut.
Some interfaces look little changed. Such as "Sync Button" and "Open-Closed-All selecting button" position.
Issues list height look too wide. Responsible, or customizable would be good.
If i can make the issues interface look like file-tree-view, that would be also good.

I think It could be too much, almost same as github mobile browser..
But if it can, will be very good. Always thank for package.

**Comment by ryaninvents** [comment]
Thanks! It would help me keep track if you created a separate issue for each of these and used the "enhancement" label 😃
